ktor:
  application:
    modules:
      - eu.franz1007.gpstracker.ApplicationKt.module
  deployment:
    port: 8090
storage:
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
  user: "root"
  driver: "org.h2.Driver"
  password: ""