CREATE TABLE IF NOT EXISTS trackgroups (id BIGSERIAL PRIMARY KEY, uuid uuid NOT NULL, "name" TEXT NOT NULL);
CREATE INDEX trackgroups_uuid ON trackgroups (uuid);
CREATE SEQUENCE IF NOT EXISTS TrackGroups_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE tracks ADD "groupId" BIGINT NULL;
ALTER TABLE tracks ADD CONSTRAINT fk_tracks_groupid__id FOREIGN KEY ("groupId") REFERENCES trackgroups(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
