CREATE TABLE IF NOT EXISTS gpspositions (id BIGSERIAL PRIMARY KEY, lat DOUBLE PRECISION NOT NULL, lon DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS tracks (id BIGSERIAL PRIMARY KEY, uuid uuid NOT NULL, "startTimestamp" TIMESTAMP NOT NULL, "endTimestamp" TIMESTAMP NOT NULL, category INT NOT NULL);
CREATE INDEX tracks_uuid ON tracks (uuid);
CREATE TABLE IF NOT EXISTS gpspoints (id BIGSERIAL PRIMARY KEY, "timestamp" TIMESTAMP NOT NULL, hdop DOUBLE PRECISION NOT NULL, altitude DOUBLE PRECISION NOT NULL, speed DOUBLE PRECISION NOT NULL, bearing DOUBLE PRECISION NOT NULL, eta TIMESTAMP NOT NULL, etfa TIMESTAMP NOT NULL, eda INT NOT NULL, edfa INT NOT NULL, position_id BIGINT NOT NULL, track_id BIGINT NOT NULL, CONSTRAINT fk_gpspoints_position_id__id FOREIGN KEY (position_id) REFERENCES gpspositions(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_gpspoints_track_id__id FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS GpsPositions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS Tracks_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS GpsPoints_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
